### ISSUE TITLE
log is required for setup but not in the schema

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#102]
In other words, fix logging, see 4.2.  

Also, I hate logging with teh fire of a thousand suns.
'

**Comment by motin** [comment]
Related: https://github.com/mozilla/shield-studies-addon-utils/issues/101

**Comment by motin** [comment]
I removed the requirement of log in studySetup in v5 (#120) - as a starting point. There is now no discrepancy between the schema and this requirement. Closing this in favor of the discussion in https://github.com/mozilla/shield-studies-addon-utils/issues/139
