### ISSUE TITLE
can't load stage-2-shield-study example in nightly

### ISSUE THREAD

**Issue by gasolin** [mozilla/shield-studies-addon-utils#103]
I build stage-2-shield-study example https://github.com/mozilla/shield-studies-addon-utils/tree/master/examples/stage-2-shield-study

and try to load on `about:debugging`. The same xpi can be loaded in v56. But in nightly it always shows error 

`There was an error during installation: Add-on shield-example-addon@mozilla.com is not compatible with application version. add-on minVersion: 53.0. add-on maxVersion: *.`

Is shield study addon still work after v57? how do I test it?

**Comment by gasolin** [comment]
I guess this is the current solution https://github.com/mozilla/shield-studies-addon-utils/issues/93
Will give it a try

**Comment by gasolin** [comment]
https://github.com/gregglind/template-shield-study works, maybe we can add the link in the example's README

**Comment by gregglind** [comment]
That is all deprecated.  Follow Mozilla/shield-studies-addon-template .
Docs corrections are all coming literally today.

**Comment by motin** [comment]
Vote for close. 
The link to the most recent example study and template is https://github.com/mozilla/shield-studies-addon-template
