### ISSUE TITLE
Clean up repository branches

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#111]
- [x] Delete all merged branches:

- 71-web-extensions
- candidate-for-v4
- coverage
- fix-first-variations-example-code
- fix-ineligible-study-js
- fix-isolate-step-code
- refactor-to-classes

- [ ] @gregglind: Move all work-in-progress branches to developer-specific forks (these can then in turn be either deleted or sent as pull requests to the main repo when they are ready for review)
 
- 10-shadow-pref
- 14-refactor-clearer-example
- 17-simplify-packet
- 5-ci-server
- 6-double-call-survey-on-expired
- bootstrap
- DOCS-sprint-base
- mozilla/71-web-extensions
- v3-shield-packet-format
- web-extension

After this, the repo will have only the following branches:

- gh-pages
- master

This lowers the barriers to contribute to this repo and makes the PR+review workflow easier.

**Comment by biancadanforth** [comment]
@gregglind , any objections to me deleting [branches](https://github.com/mozilla/shield-studies-addon-utils/branches/all) for which you closed the PR without merge?
What about branches you pushed but never opened a PR for?

**Comment by motin** [comment]
Let's wait for gregg to confirm that indeed this repo has been forked to https://github.com/gregglind/shield-studies-addon-utils so that no work-in-progress branches are completely deleted. Once they are safely copied there, we should be able to delete them from this repo since any work-in-progress should live in forks and submitted by PRs when ready, rather than live as permanent forks in the main repo.

**Comment by gregglind** [comment]
Done.  Only 
- master
- develop
- gh-pages

remain.
(Even then, gh-pages might get killed at some point.)
