### ISSUE TITLE
Delete/Close all old issues/PRs/branches

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/shield-studies-addon-utils#117]
If there's anything valuable in these old artifacts, let's create a new issue that distills all of that in one place. Ideally we have only recently made PRs/issues that are still relevant and clearly defined at the end.

**Comment by motin** [comment]
Good idea. This issue is fine for that purpose. Suggested rename: **Review and distill anything valuable in older issues/PRs/branches before closing them**

**Comment by gregglind** [comment]
closing as duplicate of #112
