### ISSUE TITLE
[v5] [develop] Should we use TypeScript for study API bundling?

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#138]
I suggest this is done as a step towards merging ideas from pioneer-utils (https://github.com/mozilla/shield-studies-addon-utils/issues/128, https://github.com/mozilla/pioneer-utils/issues/25)

Using TypeScript makes it easier to write and manage clean code, and since Pioneer Utils is already written in TypeScript, we already have a working tested webpack setup which otherwise would need to be abandoned, and we can import code directly from pioneer-utils without having to remove type definitions.

**Comment by motin** [comment]
Ping @rehandalal @gregglind for comments on this

**Comment by gregglind** [comment]
I am open to it.  I worry that it will slow things down a little, and that
it adds a build step that isn't obvious.

**Comment by rehandalal** [comment]
Sorry I totally forgot that pioneer utils master was in TypeScript but that is not the version of pioneer-utils we use.

This is the branch you want to use as the basis for pioneer-utils when porting it over...
https://github.com/mozilla/pioneer-utils/tree/v1.0.x

**Comment by motin** [comment]
@rehandalal That is very important information, thanks :) (Maybe you want to rename the master branch to develop, or typescript-experiment etc to clarify the intent. If it is not sure to be used at all, consider deleting it or moving it to a private fork)
