### ISSUE TITLE
[v5] [develop]  Magic, side effects, sending shield-study pings

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#141]
For things like `startup`, should that be side effect of utils, part of the idiomatic / boilerplate `background.js` or something else?  Maybe it's a 'first script' in the background js key on manifest, to be copied and edited from the ssau repo?  

Discussion welcome.

**Comment by motin** [comment]
Here is an example of code that would be required by the study add-on boilerplate in case we want to remove the magic of the study API with regards to choosing a variation based on studySetup:

```
    const clientId = await this.getTelemetryId();
    const studyName = this.studySetup.study.studyName;
    fraction = await this.sampling.hashFraction(studyName + clientId, 12);
    return this.sampling.chooseWeighted(weightedVariations, fraction);
```

The decision to choose a variation based on these factors should not be up to the study add-on developer, but rather the utils.

**Comment by motin** [comment]
Also related: [v5] Add tests and test utils for testing persistent and restart features #143
