### ISSUE TITLE
Meta: Labeling / naming conventions for issues

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#144]
Are we using Github labels to specify "v5" and/or adding "[v5]" to the issue name?
Same question regarding issues targeting the develop branch. Should we decide that all issues that are v5 target develop branch until further notice, since it is the current unstable version? That way we don't have to clarify "[develop]" in the issue names

**Comment by motin** [comment]
I suggest to drop "[v5]" and "[develop]" from issue names and use milestones and labels instead

**Comment by gregglind** [comment]
[v5] is clear for now, unless it's on some weird branch maybe?
