### ISSUE TITLE
[v5] Require variation for setup to eliminate setVariation

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#147]
From https://github.com/mozilla/shield-studies-addon-utils/issues/101

**Comment by motin** [comment]
Not sure exactly what this is about, but here is an example of code that would be required by the study add-on boilerplate in case we want to remove the magic of the study API with regards to choosing a variation based on studySetup:

```
    const clientId = await this.getTelemetryId();
    const studyName = this.studySetup.study.studyName;
    fraction = await this.sampling.hashFraction(studyName + clientId, 12);
    return this.sampling.chooseWeighted(this.studySetup.weightedVariations, fraction);
```

The decision to choose a variation based on these factors should not be up to the study add-on developer, but rather the utils, so eliminating setVariation from the utils would not be a great idea in that perspective.

**Comment by gregglind** [comment]
My claims around this:
- after `configure` or `setup` the study should have its variation set, and will be ready to send telemetry`
- Sometimes studies need to choose variations in ways that are strange (for example, re-using a previous branch name, debugging from a pereference).  

My bid (which I am taking), is to have `deterministicVariation` available, which does the magic.  

I am debating options around `studyPattern = shield|pioneer` as a required thing in the config, but am open to ideas.

**Comment by gregglind** [comment]
Done in #173
