### ISSUE TITLE
request: eslint max len ignore strings and templates

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#155]
Good morning!

Claim: I think we should ignore max-len for both templates and strings.  Open to ideas others.  Mind implementing?

https://github.com/ljharb/eslint/commit/91df35f912c460151f6175e1c55072d2fe00f727

```
    "max-len": [
      "warn",
      {
        code: 80,
        ignoreComments: true,
        ignoreTrailingComments: true,
        ignoreUrls: true,
        // NEU:  these are new!
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
      },
    ],
```

It's your file though :)

**Comment by motin** [comment]
What do we gain by ignoring max-len as opposed to keeping it at warn-level?
Note: npm run format already attempts to format lines to <80 automatically, so these warnings should be few in general

**Comment by gregglind** [comment]
They are warnings that clutter up the run / linting.

**Comment by pdehaan** [comment]
I'm fine with either:

(A) Removing the `max-len` rule completely and letting `npm run format` handle line length formatting.
(B) Adding two new `ignore*` properties.

Personally, I'm never really bothered by line lengths, so I'm not a big proponent of the rule.

**Comment by motin** [comment]
Closing since `npm run format` handles line length formatting, which works well enough in most cases.
