### ISSUE TITLE
Npm run format as git pre-commit hook

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#157]
This would ensure that all code that gets committed does not produce linting errors and is properly formatted, leading to more efficient reviews and experiences throughout collaboration. 

Data supporting the need for this are the many commits that are specifically only there as a result of forgetting to run `npm run format`.

(Note: [It is still possible to bypass commit hooks by using --no-verify](https://www.npmjs.com/package/pre-commit))

**Comment by gregglind** [comment]
(I am okay with this, might merge it during the next round of 'process fixing' stuff.)
