### ISSUE TITLE
Suggestion:  either jsdoc the things, or let's dump the requirement.

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#163]
For the API, I claim the api docs are better than the the autogen garbage.  The api is VERY LONG, seems like it should be built from an existing object and facade those methods.

**Comment by motin** [comment]
We should be good with the actual API docs in schema.yaml. Keeping jsdoc and API docs in sync will be problematic (and not likely to happen). Jsdoc should be optional.

**Comment by gregglind** [comment]
We jsdoc'd the things.
