### ISSUE TITLE
drop `onReady` signal

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#166]
setup is only called once per study and can be a simple promise return with the info.

**Comment by motin** [comment]
The original reason for the study:onReady event was to ensure that the event (and thus the study) only fired once, and only if it should. As an add-on developer it is pretty sweet to have a guarantee that the onReady event behaves like this. Put our add-on-specific code inside that handler and we are good to go :)
If we drop the event, we will need to throw an Exception in case the study should not run, and include relevant try/catch boilerplate in study.js

**Comment by gregglind** [comment]
I am okay with leaving this in.  I think it’s not strictly necessary but
it’s okay.  We already return the same value.

**Comment by motin** [comment]
I am for dropping it and instead using await. It is rather ugly to have to wait for the onReady event and using the onEndStudy as sort of an exception handler.

**Comment by gregglind** [comment]
Sounds fine then.

So the revised flow:
- listen for onEndStudy
- studySetup.

If you call studySetup again it’s a no op

**Comment by motin** [comment]
Until #168 is fixed, we should keep the onReady event for now, since we have no way of building a reliable try/catch around browser.study.setup() in background.js.

**Comment by motin** [comment]
#168 is now fixed, so we can drop the onReady event as long as we have a proper way to bail out in case the endStudy event was triggered by setup().

**Comment by motin** [comment]
Closing this since we de facto did not drop it in v5. This issue can be re-opened for v6+ if relevant, but not in v5 in order to keep API compatibility
