### ISSUE TITLE
Figure out if/how/when add-ons can know which error was thrown by our web extension APIs

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#168]
We can catch privileged exceptions as long as they are thrown in async environments. Currently however we can't know which error was thrown, only that an error was thrown (every error caught by add-ons are reported as `Error: An unexpected error occurred`)

(Errors thrown outside async environments can not even be caught it seems)

**Comment by aswan** [comment]
@motin I may have misunderstood your question, but there is some documentation about how to generate specific Errors from extension APIs in this section:
https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/functions.html#implementing-a-function-in-the-main-process
