### ISSUE TITLE
during user uninstall, isn't firing survey

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#194]
## To Repro:

1.  in a study (such as `example/small-study`), the user `about:addons` and user-disables the addon.  

## What does happen:

1.  OK:  Telemetry (for `user-disable`, and `exit` is sent
2.  NOT OK:  the `onEndStudy` signal is NOT received.  

Implications:  
1.  If we want to open surveys for 'user-disable', we have to do it at the 'Dangerous' layer, and not at the 'webExtension' layer.

## Possible Causes

1.  `getApi` is no longer available.  

## What next?

1.  Option 1:   Use `Services.wm` to FORCE OPEN a tab for the survey. 
- this is different than other behaviour, where the webExt does that tab opening work, OPTIONALLY. It requires documentation to explain this, and how it's weird.
- it's hard to test.
2.  Option 2:  Accept it *as is*.  Benefits:  no weird coding. 
3.  Option 3:  (Preferred, Pie in the sky).   Make it that addon uninstalls come with a 'reason' code.

**A curveball**
- [when normandy uninstalls a shield addon, it *looks* like  a user-disable](https://github.com/mozilla/shield-studies-addon-utils/issues/188)
- this means that if a normandy 'revoke' happens (for example, an addon bug), EVERYONE will get surveyed, as though they uninstalled it.  
- therefore, as a pattern, should we just 'ignore' surveying during 'user-disable'.

GL

**Comment by aswan** [comment]
Do you just want to open a particular url when the extension is uninstalled?
There's an API for that:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/setUninstallURL

**Comment by motin** [comment]
@aswan That is possible a good API to cover the case of a debrief survey specifically for add-on-installation, but as long as [when normandy uninstalls a shield add-on, it looks like a user-disable](https://github.com/mozilla/shield-studies-addon-utils/issues/188), we can't use it without risking survey URLs opening in the wrong situation.

**Comment by gregglind** [comment]
This will be solved by #246 once implemented.
