### ISSUE TITLE
Documentation/Wiki needs

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/shield-studies-addon-utils#20]
Interested stakeholders/community need a place to find information about Shield Studies and Shield in General. Here are some of things I think we need to address:
- What types of things can be Shield Studies?
- What types of things should be Heartbeat Studies?
- How does something become a study?
- What is the current pipeline for Shield Studies?
- Where can I see results from previous studies?
- On a per study basis, tell me:
  1. Average offers per day for enrollment
  2. Average click thru for offer
  3. Common abandonment rate after click thru
- Screenshots of what it looks like in Firefox

**Comment by MattGrimes** [comment]
- Can I propose a Shield Study? How?
- Can I run my own Shield Study? How and what parts do I own vs SI Team?

**Comment by motin** [comment]
Current wiki articles contain the answers to many of these questions. Links: 
https://wiki.mozilla.org/Firefox/Shield
https://wiki.mozilla.org/Firefox/Shield/Shield_Studies

**Comment by motin** [comment]
Closing in favor of new docs at https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiment
