### ISSUE TITLE
Utils v5 does not work with Firefox Beta

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#200]
Utils v5 works with release, nightly and dev edition, but [not beta](https://circleci.com/gh/motin/shield-studies-addon-utils/53?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by motin** [comment]
@aswan Could you help us debug this?

Reproduce by checking out the current master or release/5.0.1 branches and run:

```
FIREFOX_BINARY=firefox npm run test-only
FIREFOX_BINARY=beta npm run test-only
FIREFOX_BINARY=firefoxdeveloperedition npm run test-only
FIREFOX_BINARY=nightly npm run test-only
```

Only beta tests will fail, using the latest available versions for each of the above.

By using KEEPOPEN=1 (`KEEPOPEN=1 FIREFOX_BINARY=beta npm run test-only`) and then clicking on the `onEveryExtensionLoad` button we see that we get `TypeError: browser.study is undefined` in the browser console, but how do we know why our wee does not load?

**Comment by motin** [comment]
This was inaccurately closed by Github logic. Re-opening.

**Comment by wisniewskit** [comment]
I believe you'll need a signed XPI for extension API experiments to work on beta/release.

**Comment by gregglind** [comment]
They test fine in release,  but NOT beta.  That is what is so weird :)

**Comment by wisniewskit** [comment]
Heh. Yes, they do right now, but they may not for the next release (the one in beta) :)

**Comment by motin** [comment]
@wisniewskit Indeed. I installed the signed add-on from https://bugzilla.mozilla.org/show_bug.cgi?id=1469546 and it works splendid on Firefox Beta. This issue is resolved as invalid.
