### ISSUE TITLE
Are standalone web extension experiments better than bundled?

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#201]
We are currently bundling the WEEs together with the study add-ons. Pros with bundled WEEs:
 - Not have to co-install two extensions at once in order to ship studies via Normandy
 - The study add-on gets access to the bundled WEE API, which may be more secure. 
 - Ordinary extension tooling (like web-ext) works out of the box (not sure if web-ext can co/pre-install standalone WEEs for instance)

On the flip side, if we use standalone web extension experiments we will no longer be affected by the limitations of bundled WEEs, especially regarding the ability to listen to study add-on uninstall events properly (https://github.com/mozilla/shield-studies-addon-utils/issues/194)

**Comment by aswan** [comment]
@wisniewskit mentioned this today as well.
This is doable but it is woefully under-documented.  To make it work, the extension that provides an experimental API must have an id of the form `name@experiments.addons.mozilla.org`.  Then an extension that wants to use that API must include `experiments.name` in its required permissions.  Note that this will make the experimental API available to *any* webextension so APIs that should not be exposed to the world should be placed behind the `mozillaAddons` permission as well.

**Comment by motin** [comment]
Closing. For the purposes of self-contained study add-ons that manage their own lifecycle, bundled web extension experiments are better currently.
