### ISSUE TITLE
Launch post survey when study expires - v5 rc

### ISSUE THREAD

**Issue by punamdahiya** [mozilla/shield-studies-addon-utils#203]
Latest v5 currently fails to launch post survey at the end of study and should be updated to provide that. This is needed to get feedback from users on cloud storage study #173

**Comment by motin** [comment]
This was inaccurately closed by Github logic. Re-opening.

**Comment by motin** [comment]
@punamdahiya Quick update: Expiration logic and tests were improved in utils v5.0.1, and opening survey at end of study works in [the latest template code](https://github.com/mozilla/shield-studies-addon-template). I see no open issue about this against the cloudstorage add-on repo (https://github.com/mozilla/shield-cloudstorage/issues) - what are the steps to reproduce this in your add-on?

**Comment by punamdahiya** [comment]
@motin do we need to set "shield-studies-addon-utils" to version "5.0.2" to bring in this fix. This issue can be replicated by force expiring the study. 

From our discussion last week one way to do so is by setting first run time stamp shield.cloudstorage-webextensionexperiment_shield_mozilla_org.firstRunTimestamp pref to 1 in about:config. Is that still valid?

**Comment by motin** [comment]
After sorting out expiration issues, I noted that the survey launches on expiration, so this ought to be fixed as soon as 5.0.2 ships.
