### ISSUE TITLE
having to rebuild / re-sign during final deploy seems weird and wrong.

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#211]
- testing flags
- addon name

Let's think if we can avoid this

**Comment by motin** [comment]
Agree, we should be able to ship the exact build that was tested and green-lighted by QA.

> Testing flags

By controlling these through prefs there is no need to change the code in final deploy.

>  Addon name

Why is this being changed in final deploy?

**Comment by motin** [comment]
Closing since we have testing overrides from 5.1.0 https://github.com/mozilla/shield-studies-addon-utils/pull/259
