### ISSUE TITLE
Expose the tools we used for web extension experiment API development to add-on developers

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#213]
To be able to quickly generate and develop [five new APIs used in a study add-on](https://github.com/motin/taar-experiment-v3-shield-study/tree/develop/src/privileged), I extracted and exposed the tools we used for web extension experiment API development to consumers of the shield-studies-addon-utils package in https://github.com/mozilla/shield-studies-addon-utils/pull/207, calling them `weeUtils` (short for web extension experiments utils)

gregglind commented in https://github.com/mozilla/shield-studies-addon-utils/pull/210#pullrequestreview-130793676:

> I am not loving "weeUtils" as a name, but I don't have one to suggest. I do like the idea of stuff to help out authors. I am not sure that this is the best way to document and create that.

**Comment by motin** [comment]
I propose that these be moved to a separate repository (`mozilla/webext-experiment-utils` or similar) so that they can be used by other add-on authors that wish to author web extension experiments.

**Comment by motin** [comment]
I created a stand-alone repository here: https://github.com/motin/webext-experiment-utils, for use in [a separate project](https://github.com/mozilla/OpenWPM-WebExtension-Experiment). So far it was been very pleasant to be able to use wee schema verification, docs generation and stub api generation :)

**Comment by gregglind** [comment]
I like that name a lot better.  Much more descriptive.

**Comment by motin** [comment]
This has been addressed. The tools are now available in https://github.com/mozilla/webext-experiment-utils
