### ISSUE TITLE
Do add-ons with bundled web extension experiments need to be signed to work on branded builds?

### ISSUE THREAD

**Issue by motin** [mozilla/shield-studies-addon-utils#214]
From the discussions in https://github.com/mozilla/shield-cloudstorage/pull/38#pullrequestreview-127372806 and https://github.com/mozilla/shield-studies-addon-utils/issues/200 it is clear that we need a definite answer to this asap :)

**Comment by motin** [comment]
The answer seems to be: Yes. I installed the signed add-on from https://bugzilla.mozilla.org/show_bug.cgi?id=1469546 and it works splendid on Firefox Beta. Seems to be a change in fx 61, requiring add-ons with web extension experiments to be signed to work.

**Comment by aswan** [comment]
Yes, if you need to test something against beta or release you can use dev edition (for beta) or an unbranded build:
https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds
