### ISSUE TITLE
Pref firstRunTimeStamp value changes on subsequent browser restart after add-on install

### ISSUE THREAD

**Issue by punamdahiya** [mozilla/shield-studies-addon-utils#215]
Study expiration relies on firstRunTimeStamp, set in prefs when add-on is installed. With cloudstorage extension this value resets to Date.now() on subsequent restart of browser after add-on install.

**Comment by punamdahiya** [comment]
Also looking at code noticed expire days 0 might not work as it will set expiration to a very large number. Is that correct?

https://github.com/mozilla/shield-studies-addon-utils/blob/ba9c2f35e86a91b63024a10f36960829e0359c5a/webExtensionApis/study/src/studyUtils.js#L380

**Comment by punamdahiya** [comment]
Pre-req
The "xpinstall.signatures.required" boolean pref is set to "false".
The "extensions.legacy.enabled" boolean pref is set tot "true".

STR: 
1. Open about:addons -> Extensions
2. Install web extension attached to https://bugzilla.mozilla.org/show_bug.cgi?id=1441949 in nightly 62
3. Notice firstRunTimestamp in about:config
4. Restart browser and check the pref value

**Comment by punamdahiya** [comment]
@motin @gregglind logged issue seen around firstRunTimeStamp pref, could it be the reason of survey not launching in extension https://github.com/mozilla/shield-studies-addon-utils/issues/203

**Comment by punamdahiya** [comment]
Please note extension attached to bug 1441949 using shield-utils v5.0.0

To build with version 5.0.1
1) Clone repo https://github.com/mozilla/shield-cloudstorage
2) Update https://github.com/mozilla/shield-cloudstorage/blob/master/package.json#L10 to 5.0.1
3) npm install
4) Inside webextension folder run web-ext build

Build file is generated under web-ext-artifacts

**Comment by gregglind** [comment]
We have the reason.

studyUtils reset is a called by the getApi call, and shouldn't :)

Working on fix.

**Comment by biancadanforth** [comment]
It looks like `StudyUtils.reset()` is called every time on Firefox startup, which clears the pref. Working with Gregg to see what's the best way to fix it without breaking everything else...

**Comment by motin** [comment]
Fix now available in 5.0.2 release candidate (https://github.com/mozilla/shield-studies-addon-utils/pull/207)

**Comment by gregglind** [comment]
Taking and fixing.  

Update to 5.0.2 please :)
