### ISSUE TITLE
sometimes surveys show AGAIN on restart after death

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#22]

**Comment by raymak** [comment]
could it be pref problems?

**Comment by gregglind** [comment]
so, things:

1. actual problem:  the cleanup function in the addon failed, addon did not uninstall
2. implication:  we should both
   a.  try / catch on cleanup
   b.  lint cleanup in specific addons

**Comment by gregglind** [comment]
also, we should probably have the 'side' listener stop itself once the addon expires.  as it happens, it is safe to multi-call

**Comment by gregglind** [comment]
Issues fixed in #27

- the listener is on class, which only goes once.
- try / catch for cleanup things.
