### ISSUE TITLE
Document how to make addons a 'shieldy' way for Fx Devs

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#222]
- mention node / npm packages
- how to do CI etc
- what we check / lint for

**Comment by motin** [comment]
Closing since @rhelmer is working on this and it is tracked elsewhere. See https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments and https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html for more information
