### ISSUE TITLE
To include in docs: What is the point of shield / experimentation

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#238]
- claim:  The point is to GET PROBES into a POPULATION so that WE CAN DO SCIENCE to make decisions.
- the engineering is designed to get those probes there.
- acceptance is always:  
  - 1.  the probes will point to a decision
  - 2.  the engineering gets the probes to the people.

**Comment by motin** [comment]
Is this a candidate for a documentation section in the utils readme?

**Comment by motin** [comment]
In https://github.com/mozilla/shield-studies-addon-utils/commit/034eb87d00d87d0a54bb804e67415f92c2422c19, the main readme starts with links to https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments which contains resources on this matter.
