### ISSUE TITLE
Despite claims to the contrary by me, Disable doesn't actually force uninstall.

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#247]
- issue: disable ALSO shuts down the getApi, so calling disable DOESN't uninstall the addon, because the signal doesn't go through.

TO FIX:  make the uninstall happen in the onShutdown method.

@motin?

**Comment by motin** [comment]
If we can't signal onEndStudy to the add-on after user-disable, then yes, we need to at least uninstall in onShutdown. 

Related: https://github.com/motin/taar-experiment-v3-shield-study passed QA with the following comment:

> We have finished testing the TAAR Experiment v3 and the following issues are still reproducible:
> 
> - https://github.com/motin/taar-experiment-v3-shield-study/issues/34 and https://github.com/motin/taar-experiment-v3-shield-study/issues/35 - The experiment can be re-enabled and re-installed, which is a wrong behavior since this is a Shield Study;
> 
> - https://github.com/motin/taar-experiment-v3-shield-study/issues/39 - The “TAAR v3” specific prefs are not reset to their default values if the study is manually removed by the user from the “about:addons” page.
> 
> 
> QA’s recommendation: YELLOW - SHIP IT CONDITIONALLY
> 
> 
> Reasoning:
> 
> As per previous discussions about this behavior, Shield Studies were not designed to be disabled and then re-enabled. That would cause weird issues with the data, so once you've opted out of a particular study you cannot re-enroll.
> 
> 
> Since this behavior is in discussion again and no final decision was made, we are suggesting to discuss this behavior and decide if it blocks or not the launch. Considering this, we recommend contacting Matt Grimes regarding a decision in the case.
> 
> 
> Other than this, the experiment looks really good.

**Comment by motin** [comment]
Related: https://github.com/mozilla/shield-studies-addon-utils/issues/231

**Comment by motin** [comment]
@gregglind Could you devise a patch for this and push it to `release/5.0.4`?
