### ISSUE TITLE
Prefs are no longer bundled in develop branch

### ISSUE THREAD

**Issue by ericawright** [mozilla/shield-studies-addon-utils#249]
I'm following instructions from https://github.com/mozilla/shield-studies-addon-utils#browserprefs
in the same way that "study" was implemented. In the package.json of the develop branch it lists "files":
<img width="288" alt="screen shot 2018-07-17 at 1 36 09 pm" src="https://user-images.githubusercontent.com/10803178/42835282-6b26bbe6-89c6-11e8-81e3-9d8b9d3ac9f2.png">

This should include the "prefs" files as well. When I install this package, it does not contain the prefs files. I believe the commit that added those files was: https://github.com/mozilla/shield-studies-addon-utils/commit/46a8996cd129bdf3b4854ce21b559ed6b436dad2, I can't seem to find when they were removed though.

**Comment by motin** [comment]
Closing since the readme now mentions that the prefs API is not yet implemented
