### ISSUE TITLE
A white artifact is wrongly displayed for an add-on using the default shield studies icon in the "about:addons" page

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/shield-studies-addon-utils#256]
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the " Search Nudges" add-on (1.4.0) installed from "https://bugzilla.mozilla.org/show_bug.cgi?id=1462136".
- The "Nudges" doorhanger was not triggered before.
- Have the following preferences in the "about:config" page:
	- "extensions.legacy.enabled" set to true;
	- create the "extensions.shield-search-nudges.variation" string with the "doshow" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "about:addons" page and click the "Extensions" tab.
3. Observe the icon displayed in the front of the "Nudges" shield study.

**[Expected result]:**
- The icon is correctly displayed and rendered.

**[Actual result]:**
- A white artifact is displayed in the left part of the icon.

**[Notes]:**
- I've talked with Mike de Boer on Slack and he said that this icon is the default one for the shield studies.
- Attached a screen shot of the issue:
![nudges icon](https://user-images.githubusercontent.com/31243259/43903402-09c9d428-9bf5-11e8-8e8d-fc2b79361b94.png)

**Comment by motin** [comment]
That icon is not in use any longer in the newer version of the template, which instead uses https://github.com/mozilla/shield-studies-addon-template/blob/develop/src/icons/shield-icon.svg without any artifacts that we are aware of. 
@gregglind Could you approve the [request to make the newer version of the template the official one](https://github.com/mozilla/shield-studies-addon-utils/issues/256)? That would solve this issue

**Comment by motin** [comment]
Closing since the official icons were updated on sep 12
