### ISSUE TITLE
Unable to install addon-utils v 5.0.4

### ISSUE THREAD

**Issue by pdehaan** [mozilla/shield-studies-addon-utils#268]
### Steps to reproduce:

```sh
$ npm init -y
$ npm i github:mozilla/shield-studies-addon-utils#release/5.0.4 -S
```

### Actual results:

```sh
$ npm i github:mozilla/shield-studies-addon-utils#release/5.0.4 -S

npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout release/5.0.4
npm ERR! error: pathspec 'release/5.0.4' did not match any file(s) known to git
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdehaan/.npm/_logs/2018-09-28T17_47_00_779Z-debug.log
```

---

**UPDATE:** Here's the versions that have been published to npm:

```sh
$ npm info shield-studies-addon-utils versions

[ '1.0.0',
  '1.0.1',
  '1.2.0',
  '2.0.0',
  '4.0.0',
  '4.1.0',
  '5.0.0',
  '5.0.1',
  '5.0.2',
  '5.0.3' ]
```

**Comment by motin** [comment]
@gregglind Can you double check that 5.0.4 is published to npm?
@pdehaan Try`npm i github:mozilla/shield-studies-addon-utils#5.0.4 -S` meanwhile. The `release/5.0.4` branch has been deleted in favor of the `5.0.4` tag.

**Comment by motin** [comment]
@gregglind If 5.0.4 is not to be published (or can't be published due to issues mentioned in https://github.com/mozilla/shield-studies-addon-utils/issues/265), then instead remove the 5.0.4 and 5.1.0 tags, approve https://github.com/mozilla/shield-studies-addon-utils/pull/266 and publish 5.1.1.

**Comment by motin** [comment]
Version 5.0.4 (and 5.1.0) has been published. @pdehaan please verify that you are able to install it, thanks.

**Comment by pdehaan** [comment]
```sh
$ npm info shield-studies-addon-utils versions

[ '1.0.0',
  '1.0.1',
  '1.2.0',
  '2.0.0',
  '4.0.0',
  '4.1.0',
  '5.0.0',
  '5.0.1',
  '5.0.2',
  '5.0.3',
  '5.0.4',
  '5.1.0' ]
```

This still fails (I think I got it from some old Shield studies before 5.0.4 was published), but probably nothing we can do about it. Plus, if somebody wants to revive an old Shield study they can now use the version published to npm:

```sh
$ npm i github:mozilla/shield-studies-addon-utils#release/5.0.4

npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout release/5.0.4
npm ERR! error: pathspec 'release/5.0.4' did not match any file(s) known to git
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdehaan/.npm/_logs/2018-11-15T23_37_39_568Z-debug.log
```

I think going forward it makes sense to publish new versions to npm and just keep bumping semver instead of relying on transient Github tags/releases.

**Comment by motin** [comment]
> I think going forward it makes sense to publish new versions to npm and just keep bumping semver instead of relying on transient Github tags/releases.

Yes, that is the plan. The release/* branches are only available before their corresponding PRs have been merged. Tags can still be used to install directly from Github though: `npm i github:mozilla/shield-studies-addon-utils#5.0.4 -S`
