### ISSUE TITLE
small-study example isn't self contained

### ISSUE THREAD

**Issue by pdehaan** [mozilla/shield-studies-addon-utils#281]
A couple of the scripts in the examples/small-study/package.json reach up into the main project directory (which makes it difficult to copy/paste the small-study as a new project; since `../../` wouldn't resolve):

https://github.com/mozilla/shield-studies-addon-utils/blob/cffa11e64cd0c2e388d64b4faf928b5025693f4b/examples/small-study/package.json#L6-L11

Not sure if it'd be easier to move the **small-study** template into its own repo so we can add **shield-study-addon-utils** as a dependency. Or, if we move the **small-study** template into the https://github.com/mozilla/create-shield-study/tree/master/templates/shield-study directory.

**Comment by motin** [comment]
https://github.com/mozilla/create-shield-study is not ready for production, but we can definitely move the small-study to a separate repo. Related: https://github.com/mozilla/shield-studies-addon-template/issues/91
