### ISSUE TITLE
remove all deps on 'simplePrefs', which doesnt handle crashes well.

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#33]
in particuar, move the 'shield.x' prefs into the main tree:  
- shield.firstrun.<theaddon>  

I kind of hate this, but I am open to ideas.  

As an alternative, wrap them in the same place, but re-wrap the pref tree in a different place as prefSvc.(the addon tree)

@raymak?  Thoughts?

**Comment by motin** [comment]
Vote for close, there are no deps on simpleprefs in current master.

**Comment by gregglind** [comment]
Correct, this is old shame from Jetpack.  

Claim:  we are stuck with firefox Prefs in general forever.
