### ISSUE TITLE
enumerate all states that a shield-study-PROJECT can be in,

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#40]
- proposed
- done
- analyzing
- published
- in the field
- waiting-reviews
- taken 
- (some others)

for the purpose of turnig these into labels, such
- code issues
- needs-legal
- needs-data
- needs-survey
- needs-analayze
- needs-writeup
- needs-deploy

**Comment by gregglind** [comment]
A project "Feature X":

- proposed
- accepted  => needs-xpi, needs-legal, needs-data, needs-privacy
- ready-to-deploy => needs-deploy
- enrolling (in field)
- problem????
- complete => needs-analysis
- published

**Comment by motin** [comment]
This has been documented at a good enough level in https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments
