### ISSUE TITLE
make isElligible and friends promise based, for questions that need to do async work

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#43]

**Comment by gregglind** [comment]
for now, a possible way of solving:

```
// index.js

const self = require("sdk/self");
const study = require("./study");

/* do async work to setup */
study.promiseAddonsList().then(
 /* attempt startup / install / phase checks */
 (study)=>study.startup(self.loadReason)
)

// study.js

class OurStudy extends shield.Study {
    // all the async work needed to setup all the stuff.
    promiseAddonsList () {
      this.addonsList = [];
      return new Promise({/*...*/})
      // resolves with the Study
    }

    isEligible () {
      // sync, once you have addonsList set
      // check this.addonsList for which are NO
    }
    /* ... */
}
```

**Comment by gregglind** [comment]
WONT FIX, but should document.

**Comment by motin** [comment]
Vote for close. The template has isEligible async with await in bootstrap.js - this should be enough as documentation / example: https://github.com/mozilla/shield-studies-addon-template/blob/master/addon/bootstrap.js#L75

**Comment by gregglind** [comment]
This is superceded by v4, v5 which expose a singleton instead of a class.  This way of doing things was simpler for some kinds of testing, but our consensus is NOT to require subclassing.   

claim: there is only one study per addon.

We already support overriding Telemetry, Branch choice, logging, and durations using other techniques.

@Osmose this was your proposal and we welcome wisdom.
