### ISSUE TITLE
Need standards for minimal SHIELD telemetry ping payload properties

### ISSUE THREAD

**Issue by jtg567** [mozilla/shield-studies-addon-utils#44]
Any spark script written with logic that depends on certain properties being present in a telemetry ping will be broken in the absence of those properties. At the least it would be ideal for `branch`, `study_name`, `study_state`, and `study_version` to be reliably present as suggested previously and depicted in the following ping:

u'payload': {u'branch': u'observe_urls',
   u'study_name': u'@context-graph-history-shield-study',
   u'study_state': u'shutdown',
   u'study_version': u'1.0.6'},
  u'type': u'shield-study'

Recently some pings of the following format have appeared and broken our existing scripts for tracking SHIELD study enrollment/participation. If an increasing number of SHIELD payloads take haphazard forms such as this it could be difficult to assess the activity of the system from a bird's-eye-view:

u'payload': {u'domain': u'https://wikipedia.org',
   u'messageClass': u'addon-logging',
   u'messageType': u'onboard',
   u'onboardInitTime': 1475522492181L,
   u'study_version': u'1.0.5'},
  u'type': u'shield-study'

Additional properties aren't problematic, it's merely the absence of basic SHIELD metadata that is.

**Comment by raymak** [comment]
We might also want some kind of payload format versioning to know what fields we can reliably expect from a ping.

**Comment by motin** [comment]
Vote for close. Seems to be taken care of by referencing the appropriate schemas in https://github.com/mozilla/shield-studies-addon-utils/blob/master/src/schemas.js

**Comment by gregglind** [comment]
This is done, by using the Schemas.
