### ISSUE TITLE
Shield Studies Utils as Embedded Web Extension

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-studies-addon-utils#45]
Web Extensions are the future!
- `jpm` and Jetpack are going away ...
- [`web-ext`](https://github.com/mozilla/web-ext) enables a very nice development workflow with file-watching and live-reloading built in
- Web Extension APIs are cross-browser so a study could theoretically be done in Chrome & Opera as well

But Web Extensions have some draw-backs ...
- No built-in way to send Telemetry pings (The Test Pilot add-on enables this by [creating a BroadcastChannel for all experiment add-ons to communicate with the Test Pilot add-on](https://github.com/mozilla/testpilot/pull/1022), which then sends Telemetry pings)
- No built-in way to change prefs.

We should work out a shield study template that leverages web extensions, addresses the telemetry & prefs challenges, and integrates the shield plumbing for splitting users up into cohorts for variate analysis.

**Comment by groovecoder** [comment]
To get started, I may just fork & branch from https://github.com/johngruen/shield-template to see if I can just get a basic web extensions code-base integrated.

**Comment by gregglind** [comment]
This is an awesome idea!

I think this is A Project, and I want to find all blockers and eliminate them.  

I see these issues as possibly blocking changeover.  Educate me as these become possible.

1.  [ ] prefs (as study storage / persistence)
2.  [ ] telemetry (both for sending packets AND making sure the user has an id)
3.  [ ] knowing the 'phase of install'
4.  [ ] self-uninstalling of addon (and recording it before the addon dies)
5.  [ ] opening tabs (for survey) WITH PROFILE INFO.

Fwiw, once a system addon for launching these lands, web-ex sounds like the right thing :)  2017-q1

**Comment by gregglind** [comment]
I doing think you mean that repo!  That is for static amo consent pages!

**Comment by motin** [comment]
Update on this issue: 
The [official template](https://github.com/mozilla/shield-studies-addon-template) has been sporting a hybrid legacy add-on / web extension workflow for quite a while now, but it still requires messaging between the web extension and legacy add-on code to workaround the limitations of the web extension apis. A first step is to remove the need for this messaging and instead craft web extension apis to remove need for legacy code for common study operations.

**Comment by motin** [comment]
Good news on this issue - this is finally happening as part of version 5 and is being tracked by https://github.com/mozilla/shield-studies-addon-template/issues/53 (Also related: https://github.com/mozilla/shield-studies-addon-template/pull/55, https://github.com/mozilla/shield-studies-addon-utils/issues/114 and the v5-label in general when browsing issues)

**Comment by motin** [comment]
> @gregglind gregglind changed the title from Create a Web Extensions template for Shield Studies to Shield Studies Utils as Embedded Web Extension 4 days ago

My comment above is related to creating a web extensions template for shield studies. We are dropping the idea of embedded web extensions in legacy add-ons. Revert the renaming of the issue?

**Comment by motin** [comment]
This is fixed with utils v5 which has now landed in master (#197)
