### ISSUE TITLE
Ability to end a study for an arbitrary reason

### ISSUE THREAD

**Issue by Osmose** [mozilla/shield-studies-addon-utils#48]
The Security Advisor study had a few extra cases where we wanted to end the study besides disabling , uninstalling, or reaching the end of the study period. It would be nice for there to be a way for studies to trigger study end for a custom reason, and be able to set specific survey URLs for those reasons in the `surveyUrls` config parameter, and for the custom reason to be included in the query arguments for the survey.

**Comment by motin** [comment]
Vote for close. Should be possible since a good while back using `studyUtils.endStudy(endingName)`.
