### ISSUE TITLE
validation inside 'report' packets

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#51]

**Comment by gregglind** [comment]
8:07 < Osmose> gregglind: Things like the study name are in the study config, and I figure when that gets passed to library code you can assert that a name
                exists to avoid situations where the study name didn't get sent to telemetry
18:07 < Osmose> This sort've assumes that telemetry is only used via the study library functions
18:07 < Osmose> But that's probably a safe thing to do

**Comment by motin** [comment]
If this is about supplying the study name in the pings sent via the study library function, then this issue can be closed since it is the current expected behavior.
