### ISSUE TITLE
Remove try {} catch (err) {//pass} statements

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-studies-addon-utils#54]
Silently swallowing errors is 💩

**Comment by gregglind** [comment]
Most of the time, yes.

I am open to suggestions about how reporting should happen here, or should be in the catch.

The main issues:
- CLAIM: study cleanup shouldn't crash the study if it fails.   This is true for most of the user defined actions.  

The battle to fight:  in the past, we had cleanup and eligible and other functions that could SLAG the addon, with absolutely no way to rescue the client.  I chose the trade-off of try/catch.  I am open to reporting.  Should there be telemetry packet sent on error?  Ideas welcome!

**Comment by gregglind** [comment]
I propose a shield-study-error packet in #55, which could help catch these.

**Comment by motin** [comment]
Vote for close. The current master has no try {} catch (err) {//pass} statements
