### ISSUE TITLE
v3 of shield packet

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#55]
# Design spec and proposed solution for Shield Data Packets

**Revision: 8, FINAL, morning 2017/01/23**  (see revlog)
**Commenters/Feedback**:  
- analysts:  Josh Gaunt, Rob Rayborn, Kamyar Ardekani
- data platform: Trink, Roberto Vitillo
- experiments engineering:  Osmose

## goals
- [x] 1. Differentiate between SHIELD-STUDY packets, and SHIELD-STUDY-ADDON packets without having  to do much parsing
- [x] 2. SHIELD-STUDY-ADDON packets have some common fields to allow 'all study' processing easily
- [x] 3. SHIELD-STUDY-ADDON packets can vary to allow for 'bespoke' analysis
- [x] 4. ~~SHIELD-STUDY-ADDON packets can have a heirarchy~~
- [x] 5. packet analysis is possible without knowing the S3 bucket structure (DOC-TYPE)
- [x] 6.  If a SHIELD STUDY addon wants COUNTABLE ADDON SPECIFIC STATES, have a format that allows it trivially
- [x] 7.  Count ENDINGS, positive, negative, neutral
- [x] 8.  Forward-only, incompatible with v2 and below.

## Analysis Support

1.  FOR EVERY STUDY:  by STUDY, BRANCH, VERSION, CHANNEL:  total INSTALLS, completions states, ineligible + telemetry outcomes.
2.  WITHIN A STUDY, see study specific outcomes.
3.  Within a Study + Outcome, allow deep analysis
4.  See existince of errors, allow some debugging.  (eventually notify)

## JSON-SCHEMAS

These 
See [shield-study-schemas](https://github.com/gregglind/shield-study-schemas)

[Full-schema link](https://github.com/gregglind/shield-study-schemas/blob/master/shield-schemas.json)  

1.  3 packets, with a common main format
2.  DOC_TYPES:  
     - `shield-study`  :  SHIELD itself (entry, exits of studies).   
     - `shield-study-addon`:  Addon-specific code, with some conventions
     - `shield-study-error`:  Errors from anything shield related.

### Common Format

- routable by DOC_TYPE
- allows debugging by study, addon version, etc.
- `data` key is different for each type.

```
  let payload = {
    version:        PACKET_VERSION,    /* 3, which is this spec */
    study_name:     this.config.name,  /* string, usually addon.id, but not required */
    branch:         this.variation,    /* string, which branch, string */
    addon_version: self.version,       /* string, manifest.json for addon version */
    shield_version: SHIELD_VERSION,    /* string shield-studies-addon-utils package.json */
    data:           jsonable of data   /* varies by DOC_TYPE and particular study, see below */
    testing:   Boolean optional /* is a testing packet.  Ignore. */
  } 

```

Example:

- version: 3
- study_name: some.study@ux.mozilla.org
- branch: observe-only
- addon_version: 1.3.2
- shield_version: 3.0.2
- data:  {...}

### A. `shield-study` packets `data` field

```
{
  packet:  'shield-study'  // id's the packet type
   study_state:  (choose one from this list)
     - enter  // ONCE,  sums is N people enrolled.  
     - exit     // ONCE,  sum is N people enrolled
     - installed
     - ineligible
     - expired   # time ran out, self-uninstall
     - user-disable
     - ended-positive
     - ended-neutral
     - ended-negative
     - active  # at most 1 per cal day, relies on user clock

   study_state_fullname:  
   - optional, null or blank means "no additional info"
   - combines with `study_state` to allow for easier study specific states, while keeping a finite packet format.

   attributes: 
   - optional string/string key value pairs
}
```

- No other keys allowed.
- No other `study_states` are allowed or accepted
- ENVIRONMENT will be sent, by default

#### State flows:
1. `enter` =>  `(installed  | inelgible)`    // These sum to N
2. `ineligible` => `exit`  // Sum to 'ineligible'
3. `installed` => `(expired | user-disabled | ended-positive | ended-negative | ended-neutral)` => `exit`  // these sum to `installed` and are mutually exclusive

- `active` fires exactly once per 24 hour period (user clock) if the user is active that day.
- All users `enter` and `exit` and must have EXACTLY ONE way they exit.

#### Analysis

1.  Across studies, "ended-positive" is consistent
2.  Within studies, use "ended-positive" + "study_state_fullname" to see all endings.
3. `enter` and `exit` will be equal
4. All endings should sum to `install`

#### `shield-study` Examples

1.  A normal state

	```
	{ study_state:  'ineligible' }
	```
2.  A **study defined** completion

	```
	// for security-advisor
	{ 
	  study_state:  'end-positive' ,
	  study_state_fullname:  'user-attempted-sync-signup'
	  attributes:  {
	    // for WITHIN ENDPOINT Analaysis, study specific
	  	 site: some.leaky.site,
	  	 prompts: '3'
	  }
	}
	```

### B. `shield-study-addon` data field

- for a specific addon, there must be well-defined format(s)
- there are benefits to accepting the 'field' format before
- by default, environment is NOT included.
- addons may report to other places, other than UT

```
{
   packet:  'shield-study-addon',
   attributes: 
   - optional string/string key value pairs

}
```

### C.  `shield-study-error` data field

Meant to reflect and model how [SENTRY](https://docs.sentry.io/clients/javascript/) does things.

Supports these:
- existence of errors
- counting of errors by source / type
- deep dive / debugging

```
{
  packet:  'shield-study-error',
  error_id:  string,
  error_source: addon|shield|firefox|unknown

  //optional
   severity:  debug|info|warn|fatal|impossible
   attributes:  string -> string mapping
   error:  string of error object
}
```

- packet, error_id, error_source are required.

Our goal in later phases is to send a transform of these packets to an error monitoring system (such as Sentry).

## revlog

- 7: worked on the error format things
- 8: updated with the last month of work.

## FAQ

1.  DOC_TYPE:  the packet type is the DOC_TYPE, which is available 1 level up, *and* repeated
2.  Addon-specific-pings.  Counting will work, IF you ALWAYS and ONLY send telemetry when the user hits the EXIT node of your UX-interaction state machine.  NO PARTIALS!

## UNFINISHED WORK / QUESTIONS 
- [x] 1.  What should happen with a packet that can't be JSON'd?  **Decided**:  They send an ERROR home.

- [x] 2.  Should there be a way of sending errors home?  Proposed:  A 'SHIELD-STUDY-ERROR' bucket?  **Decided**:  yes.
- [x] 3.  ~~Tell me if you hate any names.~~ **Decided**: All hated names are updated.
- [x] 4.  ~~Too many 'version' like fields?~~  **Decided**: Just right.
- [x] 5.  Allow packets to TURN OFF ENVIRONMENT:  Proposed, addons pings NO ENV, but CAN REQUEST it.  Error packets have environment?.    **Decided**: all packets send env.
- [x] 6.  Handle error. **Decided**:  done, using `shield-study-error` type.
- [x] 7.  Change `running` to 1x per day at most!  And at least 1x per day if running.  Rename ALIVE.  REMOVE `shutdown`.  **Decided and done**.
- [x] 8.  Endings:  END-GOOD, END-NEUTRAL, END-BAD  (ineligible, complete, uninstall)   OR  we just have STUDY-SPECIFIC-ENDED.  Decided:  3 major 'generic' endings, + ineligible, expired.  "study-specific endings" are a secondary field.
- [x] 9.  Force studies to define all endings.  **decided**
- [x] 10. is there a good way to describe 'ineligible' as an ending.  **decided** yes.
- [x] 11.  ENTERED, EXITED.  must be equal!  **decided** yes.
- [x] 12. Expand WHY all fields are both necessary and sufficient, by describing what they allow analysis.  
- [x] 13.  CANNOT CATCH ADDON STARTUP ERRORS.  Collecting these should be fx job!  Research? **decided** this is someone else's problem, and will wait for bootstrap improvements.
- [x] 14.  Should `shield study` fields allow extra fields for custom endings?  **decided** yes, see 8.

**Comment by rayborn** [comment]
> Tell me if you hate any names

_shield_version_ is preferable _utils_version_ IMO - I wouldn't know what utils was without checking the docs

>   study_state:  installed|ineligible|running|...

Are we documenting all of the standard states?  (Maybe I missed this elsewhere)

**Comment by raymak** [comment]
- I think a __payload_type__  field would be helpful: __payload_type__ would determine the schema in the data field. 

- I would prefer to see __study_state__ in all packets (even error) rather than in the data field.

**Comment by jtg567** [comment]
+1 for **payload_type**, which could solve the problem I see with shield-study-addon packets coming in variable levels of granularity:

For example, security-advisor sent (a) pings for custom **study_state**s (sync-installed-inelligible, user-converted-feature-offer, user-converted-no-offer, user-disabled-all-warnings) when participants reached that state, as well as (b) event-related pings each time the add-on activated its panel on a domain in the hacked domain list, the user clicked one of the buttons, etc.

Is there actually a fourth ping type to specify here? A = standard states, B = add-on states, C = shield errors (good idea, btw), as well as D = add-on events?

**Comment by gregglind** [comment]
@Osmose, tell me about error reporting, and Sentry!

**Comment by gregglind** [comment]
@Osmose 

- [ ] addon defined end states should allow "details"
- [ ] not much benefit to the 'field_1' thing.  Find another method.

**Comment by Osmose** [comment]
> @Osmose, tell me about error reporting, and Sentry!

Raven.js is the lib for reporting errors to Sentry from JS: https://docs.sentry.io/clients/javascript/

Seems like there are three things that can be captured, and they map pretty well to the things we'd want to capture about our errors:

- `message`
  - Human-readable error message
- `context`
  - Arbitrary object of data.
- `error`
  - JS error object used for getting a traceback.

I suggest an API like this (emphasis on suggest and like):

```js
// reportError(message, [context], [error])
// context and error are optional, error can be distinguished by checking the type.
// context can have well-known keys, like { type: 'addon' } and { type: 'lib' } for determining
// what code the error came from. study.reportError can auto-populate these since errors from within
// the study lib probably will use another method.
try {
  reticulateSplines();
} catch (err) {
  study.reportError('Error occurred while reticulating splines.', err);
}
```

**Comment by Osmose** [comment]
>     not much benefit to the 'field_1' thing. Find another method.

```json
{
  "pivot": ["value_1", "value_2"]
}
```

**Comment by gregglind** [comment]
@Osmose, updated both sections B and C above.  See if this design is better.  

- Add a "namespace" that is a 'top heirarchy'
- Add a "pivot" field that is an ARRAY of FIELDNAMES.
- then construct the xtab / pivot based on the FIELDS defined in FIELDNAMES for that 'namespace'

Drawbacks:
- relies on the first "pivot" seen within a namespace to construct the analysis
- repeats that data every packet.

**Comment by gregglind** [comment]
@Osmose re: errors, think about which things are top level and which should be in 'context', or if we need to be fussier.

**Comment by Osmose** [comment]
> @Osmose re: errors, think about which things are top level and which should be in 'context', or if we need to be fussier.

I think message is the only thing that should be outside of context, as honestly that and the traceback are the bulk of the error info we'd want.

There are some other useful things that could be in the context, some of them automagically populated:

- Firefox Version
- Firefox Channel
- OS (navigator.oscpu probably)
- Add-on version
- Add-on lib version
- Severity

That's about all I can think of.

**Comment by mreid-moz** [comment]
Please attempt to use prior art for things like collecting scalar measures (per the extended /unspecified "data"), and for things like context and stack traces, events, etc.
cc @georgf

**Comment by georgf** [comment]
> JS error object used for getting a traceback.
This sounds like potential privacy leaks. Can you make sure that there are no PII paths are leaked in the stack?

> - optional, null or blank means "no additional info"
Pick one.

(A) details sounds very free-form. How will you document and extract those fields for each study?
Could you use an approach like [scalars](http://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/collection/scalars.html#the-yaml-definition-file), allowing for automated documentation and ETL?

(B) sounds like scalar formats again or a similar data description format. Otherwise you'd have to write a schema for each study format?

What is the timeframe for v3?

**Comment by gregglind** [comment]
Updated. I think all outstanding questions are handled in version 8 of this.

**Comment by motin** [comment]
Vote for closing this issue if the current master uses packet version 3 (Which it seems to do: https://github.com/mozilla/shield-studies-addon-utils/blob/9f94a24aadcaa4e32aa1d54b6b5a5703392bb494/src/StudyUtils.in.jsm#L6)
Open another issue to track any missing documentation related to the packet structure, if necessary.
