### ISSUE TITLE
v3 documentation proposal

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#66]
- README.md, building, links it all together
- 2 examples
  - super simple (pref-flip, nothing weird at all)
  - super complex, with everything in the study overridden
- tear down ALL OLD DOCS
- process?  
- fix cli to make it all work :)

**Comment by motin** [comment]
Vote for close, or updated proposal related to v4+.

**Comment by gregglind** [comment]
v3 is dead.
