### ISSUE TITLE
Telemetry Helper Tools.

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#94]
- dump telemetry for a profile.
- anonymize those.
- add calls to telemtry archive for testing?

**Comment by gregglind** [comment]
Addon Telemetry Helper exists, but is Legacy.  Solve this in v5.

**Comment by motin** [comment]
Closing since searching sent telemetry is available both at runtime and during testing, and no other enhancements have been deemed necessary during the last few years
