### ISSUE TITLE
one file into addon (in general) script

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#95]
- makeIntoAddon funciton / cli.  Might need config from package.json?  or maybe just randomize the things?

**Comment by gregglind** [comment]
possible solutions:

- expect a startup() function to the module?
- if it's a bootstrap.js, use it as such, else make a fake bootstrap.js that calls it by path (eliminates chrome.manifest.
- generate a fake install.rdf from a template.

Also, who cares about this?
- easy to run fx code this way?  (or is it easier to use webdriver?)

**Comment by motin** [comment]
Is the purpose to facilitate testing of ssau? In that case it seems easier to have a script / cli to copy the dist to other add-on repos (like the template, or previous studies) and execute npm run firefox in those add-on directories.

**Comment by gregglind** [comment]
Correct.
