### ISSUE TITLE
How can create own mozilla browser

### ISSUE THREAD

**Issue by niksooo7** [mozilla/shield-studies-addon-utils#97]
dear sir 
how can create own browser type Mozilla browser I like and im add in mozilians please add me my name nikul from India
please sir help me own browser is im publish in android play store and earn money and send earn money mini mum earn send a Mozilla please help

**Comment by groovecoder** [comment]
This isn't the right repository to ask this project.

You can learn more about making your own application on top of Mozilla's Gecko technology here: https://developer.mozilla.org/en-US/docs/Gecko/Embedding_Mozilla
