### ISSUE TITLE
decide via user interviews how to do the template

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#98]
- how to clone / startup
- monorepo
- thick vs thin

**Comment by groovecoder** [comment]
omg yes please monorepo. I hate juggling all the repos in shavar (and the last couple days trying to figure out hindsight, lua-sandbox, lua-sandbox-extensions, mozilla-pipeline-schemas, etc.)

**Comment by motin** [comment]
+1 for not introducing more repos without careful consideration. The separation between utils and template is a good one though imo. Possibly also extract the shield-study-helper-addon from this repo to a separate repo, but that is not of high priority.

**Comment by gregglind** [comment]
reopen when we want to move the helper addon
